name: Build LowCode Platform

on:
  push: # Trigger on push to any branch
    branches: ["*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
      fail-fast: false
    env:
      tag: ${{ github.ref_name != 'main' && format('{0}-{1}', github.ref_name, github.run_id) || '' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true

    - name: Install dependencies for C++
      if: matrix.os == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcurl4-openssl-dev libopencv-dev libmysqlclient-dev

    - name: Compile ip_tracker
      if: matrix.os == 'linux'
      run: |
        mkdir -p apps/ip_tracker/bin
        g++ -std=c++11 -o apps/ip_tracker/bin/ip_tracker apps/ip_tracker/ip_tracker.cpp -lcurl

    - name: Compile image_converter
      if: matrix.os == 'linux'
      run: |
        mkdir -p apps/image_converter/bin
        g++ -std=c++11 -o apps/image_converter/bin/image_converter apps/image_converter/image_converter.cpp `pkg-config --cflags --libs opencv4`

    - name: Compile dbuser_manager
      if: matrix.os == 'linux'
      run: |
        mkdir -p apps/dbuser_manager/bin
        g++ -std=c++11 -o apps/dbuser_manager/bin/dbuser_manager apps/dbuser_manager/dbuser_manager.cpp -lmysqlclient

    - name: Create asset directories
      run: |
        mkdir -p views/assets/thirdparties/vuetify
        mkdir -p views/assets/css/sform/fontawesome
        mkdir -p views/assets/css/sform/webfonts
    
    - name: Download dependencies
      run: |
        # Extract dependencies from build.sh
        # Vue, Vuetify, Material Design Icons, Font Awesome
        dependencies=(
          "views/assets/thirdparties/vuetify/vue.js|https://cdn.jsdelivr.net/npm/vue@2.7.8/dist/vue.js"
          "views/assets/thirdparties/vuetify/vuetify.js|https://cdn.jsdelivr.net/npm/vuetify@2.6.8/dist/vuetify.js"
          "views/assets/thirdparties/vuetify/vuetify.min.css|https://cdn.jsdelivr.net/npm/vuetify@2.6.8/dist/vuetify.min.css"
          "views/assets/thirdparties/vuetify/materialdesignicons.min.css|https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.min.css"
          "views/assets/thirdparties/vuetify/materialdesignicons-webfont.eot|https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/fonts/materialdesignicons-webfont.eot"
          "views/assets/thirdparties/vuetify/materialdesignicons-webfont.ttf|https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/fonts/materialdesignicons-webfont.ttf"
          "views/assets/thirdparties/vuetify/materialdesignicons-webfont.woff|https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/fonts/materialdesignicons-webfont.woff"
          "views/assets/thirdparties/vuetify/materialdesignicons-webfont.woff2|https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/fonts/materialdesignicons-webfont.woff2"
          "views/assets/css/sform/fontawesome/brands.css|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/brands.css"
          "views/assets/css/sform/fontawesome/fontawesome.css|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/fontawesome.css"
          "views/assets/css/sform/fontawesome/solid.css|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/solid.css"
          "views/assets/css/sform/webfonts/fa-brands-400.eot|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-brands-400.eot"
          "views/assets/css/sform/webfonts/fa-brands-400.svg|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-brands-400.svg"
          "views/assets/css/sform/webfonts/fa-brands-400.ttf|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-brands-400.ttf"
          "views/assets/css/sform/webfonts/fa-brands-400.woff|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-brands-400.woff"
          "views/assets/css/sform/webfonts/fa-brands-400.woff2|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-brands-400.woff2"
          "views/assets/css/sform/webfonts/fa-solid-900.eot|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-solid-900.eot"
          "views/assets/css/sform/webfonts/fa-solid-900.svg|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-solid-900.svg"
          "views/assets/css/sform/webfonts/fa-solid-900.ttf|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-solid-900.ttf"
          "views/assets/css/sform/webfonts/fa-solid-900.woff|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-solid-900.woff"
          "views/assets/css/sform/webfonts/fa-solid-900.woff2|https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-solid-900.woff2"
        )
        
        for item in "${dependencies[@]}"; do
          file="${item%%|*}"
          url="${item##*|}"
          curl -fSL "$url" -o "$file" || { 
            echo "Failed to download $url"; 
            exit 1; 
          }
        done
    
    - name: Build Go application
      run: |
        mkdir -p build/
        GOOS=$(echo "${{ matrix.os }}" | sed 's/-latest//') GOARCH=${{ matrix.arch }} go build -o build/run-${{ matrix.os }}-${{ matrix.arch }} main.go
        cp -r views build/
        cp -r apps build/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lowcode-platform-${{ matrix.os == 'darwin' && 'macos' || matrix.os }}${{ matrix.arch }}-${{ env.tag }}
        path: build/
